#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

cabal build

maelstrom=$(nix build --file maelstrom.nix --no-link --print-out-paths)
export maelstrom

test=${1:-}

when() {
  if [ -z "$test" ] || [ "$test" = "$1" ]; then
    (set -x; "${@:2}")
  fi
}

when 1 ./maelstrom test -w echo --bin hotgoss-1 --node-count 1 --time-limit 10

when 2 ./maelstrom test -w unique-ids --bin hotgoss-2 --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition

when 3a ./maelstrom test -w broadcast --bin hotgoss-3a --node-count 1 --time-limit 20 --rate 10

when 3b ./maelstrom test -w broadcast --bin hotgoss-3b --node-count 5 --time-limit 20 --rate 10
